module:
  block: 0
  breakpoint: 0
  config: 0
  contact: 0
  datetime: 0
  dblog: 0
  entity_reference: 0
  field: 0
  field_ui: 0
  filter: 0
  link: 0
  node: 0
  options: 0
  page_cache: 0
  system: 0
  text: 0
  toolbar: 0
  user: 0
  minimal: 1000
theme:
  stark: 0
  classy: 0
  seven: 0
