module:
  block: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  contact: 0
  datetime: 0
  dblog: 0
  editor: 0
  entity_reference: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  link: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  system: 0
  text: 0
  toolbar: 0
  user: 0
  views: 0
  views_ui: 0
  minimal: 1000
theme:
  stark: 0
  classy: 0
  seven: 0
  drupalcampcebu2015: 0
